language: node_js
os:
  - linux
  - osx
node_js:
  - '12'
  - '13'
cache:
  yarn: true
  directories:
    - node_modules
git:
  depth: 5
install:
  - yarn install
script:
  - yarn lint
  - yarn build
  - yarn test
