name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest] # skip ubuntu-latest for now

    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn lint
      - run: yarn test
