name: CI

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    lint-and-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: yarn install
            - run: yarn lint
            - run: yarn test
